---

- hosts: cluster
  gather_facts: yes
  become: yes
  roles:
    - role: k3s/prereq
    - role: k3s/download
    # - role: raspberrypi

- hosts: cluster_master
  become: yes
  roles:
    - role: k3s/master

- hosts: cluster_worker
  become: yes
  roles:
    - role: k3s/worker
