---

- name: install dependencies
  become: yes
  apt:
    state: present
    update_cache: yes
    pkg:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - python3-pip

- name: install 'Docker SDK for Python'
  pip:
    name: docker

- name: add GPG key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add apt repository
  become: yes
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: install docker
  become: yes
  apt:
    state: latest
    update_cache: yes
    pkg:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: ensure docker is started & enabled
  become: yes
  service:
    name: docker
    state: started
    enabled: yes
